'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Manage

    ''' <summary>
    ''' Contrôle SuccessMessagePlaceHolder.
    ''' </summary>
    ''' <remarks>
    ''' Champ généré automatiquement.
    ''' Pour modifier, déplacez la déclaration de champ du fichier de concepteur dans le fichier code-behind.
    ''' </remarks>
    Protected WithEvents SuccessMessagePlaceHolder As Global.System.Web.UI.WebControls.PlaceHolder

    ''' <summary>
    ''' Contrôle ChangePassword.
    ''' </summary>
    ''' <remarks>
    ''' Champ généré automatiquement.
    ''' Pour modifier, déplacez la déclaration de champ du fichier de concepteur dans le fichier code-behind.
    ''' </remarks>
    Protected WithEvents ChangePassword As Global.System.Web.UI.WebControls.HyperLink

    ''' <summary>
    ''' Contrôle CreatePassword.
    ''' </summary>
    ''' <remarks>
    ''' Champ généré automatiquement.
    ''' Pour modifier, déplacez la déclaration de champ du fichier de concepteur dans le fichier code-behind.
    ''' </remarks>
    Protected WithEvents CreatePassword As Global.System.Web.UI.WebControls.HyperLink

    ''' <summary>
    ''' Contrôle PhoneNumber.
    ''' </summary>
    ''' <remarks>
    ''' Champ généré automatiquement.
    ''' Pour modifier, déplacez la déclaration de champ du fichier de concepteur dans le fichier code-behind.
    ''' </remarks>
    Protected WithEvents PhoneNumber As Global.System.Web.UI.WebControls.Label
    
End Class
